FROM ros:noetic-ros-base-focal

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3 \
    python3-catkin-tools \
    python3-future \
    python3-lxml \
    python3-pip \
    python3-serial \
    ros-noetic-geometry-msgs \
    ros-noetic-roscpp \
    ros-noetic-rospy \
    ros-noetic-std-msgs \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --no-deps pymavlink==2.4.49

WORKDIR /catkin_ws
COPY legacy_ubuntu20_image/catkin_ws/src /catkin_ws/src
RUN /bin/bash -lc "source /opt/ros/noetic/setup.bash && catkin_make"

WORKDIR /app
COPY src/ros_nodes /app/src/ros_nodes

RUN chmod +x /app/src/ros_nodes/*.py

CMD ["python3", "/app/src/ros_nodes/target_bearing_node.py"]
